// Generates src/gpu/GpuWheel.hpp: the wheel-30 tables shared by the host
// driver and the GPU kernels. The layout mirrors primesieve's own
// wheel30Init / WheelElement tables so that the GPU sieve produces a bit
// array that is identical to the one produced by the CPU sieve.
#include <cstdio>
#include <cstdint>
#include <cassert>
#include <vector>

// Residues coprime to 30, in the order primesieve assigns to sieve bits:
// bit b of a byte covers  segmentLow + byteIndex*30 + BIT_OFFSET[b].
static const int BIT_OFFSET[8] = { 7, 11, 13, 17, 19, 23, 29, 31 };
// RB[b] = BIT_OFFSET[b] % 30 -- the residue owning bit b.
static const int RB[8]         = { 7, 11, 13, 17, 19, 23, 29,  1 };
// R[i] = residues in ascending order; this is the order used for the
// multiplier k (primesieve's wheel30Init[].wheelIndex).
static const int R[8]          = { 1, 7, 11, 13, 17, 19, 23, 29 };

int main(int argc, char** argv)
{
  // residue -> bit index (RB order); -1 if not coprime to 30
  int bitOf[30]; for (int i = 0; i < 30; i++) bitOf[i] = -1;
  for (int b = 0; b < 8; b++) bitOf[RB[b]] = b;
  // residue -> index in R; -1 if not coprime to 30
  int kOf[30]; for (int i = 0; i < 30; i++) kOf[i] = -1;
  for (int i = 0; i < 8; i++) kOf[R[i]] = i;

  // ---- wheel30Init[30]: q%30 -> (step to next coprime multiplier, its k index)
  struct Init { int f, k; } init[30];
  for (int r = 0; r < 30; r++) {
    int f = 0; while (kOf[(r + f) % 30] < 0) f++;
    init[r].f = f;
    init[r].k = kOf[(r + f) % 30];
  }

  // ---- wheel30[64]: state = pIdx*8 + kIdx
  struct Elem { int unsetBit, f, correct, next; } w[64];
  for (int pi = 0; pi < 8; pi++) {
    int pr = RB[pi];                       // p % 30
    for (int ki = 0; ki < 8; ki++) {
      int kr = R[ki];                      // k % 30
      int nki = (ki + 1) % 8;
      int nkr = R[nki];
      int f   = ((nkr - kr) + 30) % 30;    // step added to k
      int mr  = (pr * kr) % 30;            // m % 30  (m = p*k)
      int mr2 = (pr * nkr) % 30;           // next multiple's residue
      assert(bitOf[mr] >= 0 && bitOf[mr2] >= 0);
      // byteIndex is measured from low = segmentLow + 6
      int rem  = ((mr  - 6) % 30 + 30) % 30;
      int rem2 = ((mr2 - 6) % 30 + 30) % 30;
      int num  = pr * f + rem - rem2;
      assert(num % 30 == 0 && num >= 0);
      w[pi*8 + ki] = { 0xff & ~(1 << bitOf[mr]), f, num / 30, pi*8 + nki };
    }
  }

  FILE* out = (argc > 1) ? fopen(argv[1], "w") : stdout;
  if (!out) { fprintf(stderr, "cannot open output\n"); return 1; }
  fprintf(out,
    "///\n/// @file  GpuWheel.hpp\n"
    "/// @brief Wheel-30 lookup tables shared by the host driver and the GPU\n"
    "///        kernels. The bit layout is identical to primesieve's CPU sieve:\n"
    "///        8 bits per 30 numbers, bit b of byte i covers\n"
    "///        segmentLow + i*30 + {7,11,13,17,19,23,29,31}[b].\n"
    "///\n"
    "///        GENERATED by tools/gen_wheel.cpp -- do not edit by hand.\n"
    "///\n"
    "/// This file is distributed under the BSD License. See the COPYING\n"
    "/// file in the top level directory.\n"
    "///\n\n"
    "#ifndef PRIMESIEVE_GPU_WHEEL_HPP\n#define PRIMESIEVE_GPU_WHEEL_HPP\n\n"
    "#include <stdint.h>\n\nnamespace primesieve {\nnamespace gpu {\n\n"
    "/// q%%30 -> step to the next multiplier coprime to 30, and that\n"
    "/// multiplier's wheel index.\nstruct GpuWheelInit { uint8_t nextMultipleFactor; uint8_t wheelIndex; };\n\n"
    "/// One wheel step: clear `unsetBit`, then\n"
    "///   multipleIndex += (prime/30) * nextMultipleFactor + correct;\n"
    "///   wheelIndex     = next;\nstruct GpuWheelElement { uint8_t unsetBit; uint8_t nextMultipleFactor; uint8_t correct; uint8_t next; };\n\n"
    "static const GpuWheelInit gpuWheel30Init[30] =\n{\n");
  for (int r = 0; r < 30; r++)
    fprintf(out, "  { %d, %d }%s%s", init[r].f, init[r].k, r == 29 ? "" : ",", (r % 6 == 5) ? "\n" : "");
  fprintf(out, "};\n\nstatic const GpuWheelElement gpuWheel30[64] =\n{\n");
  for (int s = 0; s < 64; s++) {
    if (s % 8 == 0) fprintf(out, "  /* p%%30 = %2d */\n", RB[s/8]);
    fprintf(out, "  { 0x%02x, %d, %d, %2d }%s\n", w[s].unsetBit, w[s].f, w[s].correct, w[s].next, s == 63 ? "" : ",");
  }
  fprintf(out, "};\n\n/// p%%30 -> pIdx*8, the base wheel state for a sieving prime (0 = unused).\n"
               "static const uint8_t gpuWheelOffsets[30] =\n{\n");
  int off[30] = {0};
  for (int b = 0; b < 8; b++) off[RB[b]] = b * 8;
  for (int r = 0; r < 30; r++)
    fprintf(out, "  %2d%s%s", off[r], r == 29 ? "" : ",", (r % 10 == 9) ? "\n" : "");
  fprintf(out, "};\n\n/// bit index -> offset added to segmentLow + byteIndex*30.\n"
               "static const uint8_t gpuBitOffset[8] = { 7, 11, 13, 17, 19, 23, 29, 31 };\n\n"
               "} // namespace gpu\n} // namespace primesieve\n\n#endif\n");
  if (out != stdout) fclose(out);
  fprintf(stderr, "gen_wheel: wrote tables\n");
  return 0;
}
