///
/// @file  GpuWheel.hpp
/// @brief Wheel-30 lookup tables shared by the host driver and the GPU
///        kernels. The bit layout is identical to primesieve's CPU sieve:
///        8 bits per 30 numbers, bit b of byte i covers
///        segmentLow + i*30 + {7,11,13,17,19,23,29,31}[b].
///
///        GENERATED by tools/gen_wheel.cpp -- do not edit by hand.
///
/// This file is distributed under the BSD License. See the COPYING
/// file in the top level directory.
///

#ifndef PRIMESIEVE_GPU_WHEEL_HPP
#define PRIMESIEVE_GPU_WHEEL_HPP

#include <stdint.h>

namespace primesieve {
namespace gpu {

/// q%30 -> step to the next multiplier coprime to 30, and that
/// multiplier's wheel index.
struct GpuWheelInit { uint8_t nextMultipleFactor; uint8_t wheelIndex; };

/// One wheel step: clear `unsetBit`, then
///   multipleIndex += (prime/30) * nextMultipleFactor + correct;
///   wheelIndex     = next;
struct GpuWheelElement { uint8_t unsetBit; uint8_t nextMultipleFactor; uint8_t correct; uint8_t next; };

static const GpuWheelInit gpuWheel30Init[30] =
{
  { 1, 0 },  { 0, 0 },  { 5, 1 },  { 4, 1 },  { 3, 1 },  { 2, 1 },
  { 1, 1 },  { 0, 1 },  { 3, 2 },  { 2, 2 },  { 1, 2 },  { 0, 2 },
  { 1, 3 },  { 0, 3 },  { 3, 4 },  { 2, 4 },  { 1, 4 },  { 0, 4 },
  { 1, 5 },  { 0, 5 },  { 3, 6 },  { 2, 6 },  { 1, 6 },  { 0, 6 },
  { 5, 7 },  { 4, 7 },  { 3, 7 },  { 2, 7 },  { 1, 7 },  { 0, 7 }
};

static const GpuWheelElement gpuWheel30[64] =
{
  /* p%30 =  7 */
  { 0xfe, 6, 1,  1 },
  { 0xef, 4, 1,  2 },
  { 0xf7, 2, 0,  3 },
  { 0x7f, 4, 1,  4 },
  { 0xbf, 2, 1,  5 },
  { 0xfb, 4, 1,  6 },
  { 0xfd, 6, 1,  7 },
  { 0xdf, 2, 1,  0 },
  /* p%30 = 11 */
  { 0xfd, 6, 2,  9 },
  { 0xf7, 4, 1, 10 },
  { 0x7f, 2, 1, 11 },
  { 0xdf, 4, 2, 12 },
  { 0xfe, 2, 0, 13 },
  { 0xbf, 4, 2, 14 },
  { 0xfb, 6, 2, 15 },
  { 0xef, 2, 1,  8 },
  /* p%30 = 13 */
  { 0xfb, 6, 2, 17 },
  { 0x7f, 4, 2, 18 },
  { 0xdf, 2, 1, 19 },
  { 0xef, 4, 2, 20 },
  { 0xfd, 2, 1, 21 },
  { 0xfe, 4, 1, 22 },
  { 0xbf, 6, 3, 23 },
  { 0xf7, 2, 1, 16 },
  /* p%30 = 17 */
  { 0xf7, 6, 3, 25 },
  { 0xbf, 4, 3, 26 },
  { 0xfe, 2, 1, 27 },
  { 0xfd, 4, 2, 28 },
  { 0xef, 2, 1, 29 },
  { 0xdf, 4, 2, 30 },
  { 0x7f, 6, 4, 31 },
  { 0xfb, 2, 1, 24 },
  /* p%30 = 19 */
  { 0xef, 6, 4, 33 },
  { 0xfb, 4, 2, 34 },
  { 0xbf, 2, 2, 35 },
  { 0xfe, 4, 2, 36 },
  { 0xdf, 2, 1, 37 },
  { 0x7f, 4, 3, 38 },
  { 0xf7, 6, 4, 39 },
  { 0xfd, 2, 1, 32 },
  /* p%30 = 23 */
  { 0xdf, 6, 5, 41 },
  { 0xfd, 4, 3, 42 },
  { 0xfb, 2, 1, 43 },
  { 0xbf, 4, 3, 44 },
  { 0x7f, 2, 2, 45 },
  { 0xf7, 4, 3, 46 },
  { 0xef, 6, 5, 47 },
  { 0xfe, 2, 1, 40 },
  /* p%30 = 29 */
  { 0xbf, 6, 6, 49 },
  { 0xdf, 4, 4, 50 },
  { 0xef, 2, 2, 51 },
  { 0xf7, 4, 4, 52 },
  { 0xfb, 2, 2, 53 },
  { 0xfd, 4, 4, 54 },
  { 0xfe, 6, 5, 55 },
  { 0x7f, 2, 2, 48 },
  /* p%30 =  1 */
  { 0x7f, 6, 1, 57 },
  { 0xfe, 4, 0, 58 },
  { 0xfd, 2, 0, 59 },
  { 0xfb, 4, 0, 60 },
  { 0xf7, 2, 0, 61 },
  { 0xef, 4, 0, 62 },
  { 0xdf, 6, 0, 63 },
  { 0xbf, 2, 0, 56 }
};

/// p%30 -> pIdx*8, the base wheel state for a sieving prime (0 = unused).
static const uint8_t gpuWheelOffsets[30] =
{
   0,  56,   0,   0,   0,   0,   0,   0,   0,   0,
   0,   8,   0,  16,   0,   0,   0,  24,   0,  32,
   0,   0,   0,  40,   0,   0,   0,   0,   0,  48
};

/// bit index -> offset added to segmentLow + byteIndex*30.
static const uint8_t gpuBitOffset[8] = { 7, 11, 13, 17, 19, 23, 29, 31 };

} // namespace gpu
} // namespace primesieve

#endif
